title: Dylan W's Blog
description: 愿世界更加美好
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

giscus:
  repo: zungmou/learn
  repo_id: R_kgDOSaWeSw
  category: Announcements
  category_id: DIC_kwDOSaWeS84C81Q1
  mapping: pathname
  reactions_enabled: "1"
  theme: light
  lang: zh-CN

collections:
  thoughts:
    output: true
    permalink: /thoughts/:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "thought"

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

category_names:
  cs: 计算机科学
  tech: 技术
  life: 生活
  thought: 想法
